maintainer       "Keno Fischer"
maintainer_email "kfischer@college.harvard.edu"
license          "MIT"
description      "Configures the Jenkins server for use by the Julia Project"
version          "0.1"
depends "jenkins"
